export const buek = [
    'valaki a wc-ben rókázik 🤮', 
    'valaki csókolózik nem a párjával 💋', 
    'kiürül egy tömény 😋', 
    'valaki kártyatrükköt mutat be 🪄', 
    'valaki felhozza, hogy szingli 😥', 
    'legalább 5-en shotoznak 🥃', 
    'valaki elsírja magát 🥺', 
    'valaki eltör valamit 🥴', 
    'valaki hazamegy 🏠', 
    'legalább 4-en szelfiznek együtt 📸',
    'legalább 3 ember társasozik 🎲', 
    'valaki hangosan énekel 🎤', 
    'Áder János beszédet mond 🇭🇺', 
    'valaki toastot mond 🥂', 
    'valaki elesik 🤕',
    'valaki BUÉK üzenetet kap 💬', 
    'valaki szétlocsol egy pezsgőt 🍾', 
    'tüzijátékot látunk ✨', 
    'valaki dudát fúj 🎉', 
    'valaki dohányzik, aki amúgy nem szokott 🚬',
    'valaki felhívja a szüleit ☎️', 
    'legalább 5 ember ivósjátékozik 🎲', //22
    'legalább 3 ember egyszerre táncol 🕺🏻', 
    'valaki taktikai evést folytat 🍞',
    'valaki újévi fogadalmat tesz 🥗',
    'valaki panaszkodik, mert hangosan bulizunk 🤬',
    'random emberek csatlakoznak a bulihoz 🙋🏼‍♀️',
    'valaki hangszeren játszik 🎹',
    'legalább 5 ember a himnuszt énekli 🎼',
    'legalább 3 ember TV kabarét néz 🤹🏻‍♀️',
    'valaki átöltözik 👗',
    'valaki kültéren pisil 🤫',
    'valaki lehány valakit 🤢',
    'valaki az exével textel ❤️‍🩹',
    'a 3. üveg bor kiürül 🍷',
    'az 5. üveg pezsgő kiürül 😵‍💫',
    'valaki véletlenül kiborítja az italát 😩',
    'legalább 5-en pálinkáznak 🍄',
    'valaki bealszik 😴',
    'helyszínt vált a buli ⛺️',
    'felkel a nap 🌄',
    'valaki fancy koktélt kever 🍹',
    'valaki nem alkoholizál legalább éjfélig 🤰🏽',
    'valaki social mediára posztol 👩🏼‍💻',
    'valakin szilveszteri hacuka van 🤡',
    '4 elhagyott pohár keletkezik ❓',
    'valakinek lemerül a telefonja 📲',
]

export const buekJoker = '2️⃣0️⃣2️⃣2️⃣'
